# Generated by Django 6.0.6 on 2026-09-11 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_leadershipanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichmentDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('source_path', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='EnrichmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=512)),
                ('seed', models.JSONField(blank=True, default=dict)),
                ('fields', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='new', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrichment_records', to='warehouse.company')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='warehouse.enrichmentdataset')),
            ],
            options={
                'ordering': ['dataset_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EnrichmentProviderRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(max_length=16)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('ran_at', models.DateTimeField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_runs', to='warehouse.enrichmentrecord')),
            ],
        ),
        migrations.CreateModel(
            name='EnrichmentGoldenField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(db_index=True, max_length=64)),
                ('value', models.JSONField()),
                ('confidence', models.FloatField()),
                ('provider', models.CharField(max_length=128)),
                ('ev_url', models.CharField(blank=True, max_length=1024)),
                ('rivals', models.IntegerField(default=0)),
                ('contested', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golden_fields', to='warehouse.enrichmentrecord')),
            ],
        ),
        migrations.CreateModel(
            name='EnrichmentClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(db_index=True, max_length=64)),
                ('value', models.JSONField()),
                ('value_hash', models.CharField(max_length=40)),
                ('confidence', models.FloatField()),
                ('provider', models.CharField(db_index=True, max_length=64)),
                ('verified', models.BooleanField(default=False)),
                ('ev_url', models.CharField(blank=True, max_length=1024)),
                ('ev_snippet', models.TextField(blank=True)),
                ('ev_locator', models.CharField(blank=True, max_length=255)),
                ('retrieved_at', models.DateTimeField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='warehouse.enrichmentrecord')),
            ],
        ),
        migrations.AddIndex(
            model_name='enrichmentrecord',
            index=models.Index(fields=['dataset', 'status'], name='warehouse_e_dataset_b4d5f7_idx'),
        ),
        migrations.AddIndex(
            model_name='enrichmentrecord',
            index=models.Index(fields=['company'], name='warehouse_e_company_affb83_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrichmentrecord',
            constraint=models.UniqueConstraint(fields=('dataset', 'source_key'), name='enrichment_record_dataset_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='enrichmentproviderrun',
            index=models.Index(fields=['provider', 'status'], name='warehouse_e_provide_a61e52_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrichmentproviderrun',
            constraint=models.UniqueConstraint(fields=('record', 'provider'), name='enrichment_provider_run_uniq'),
        ),
        migrations.AddIndex(
            model_name='enrichmentgoldenfield',
            index=models.Index(fields=['field', 'contested'], name='warehouse_e_field_ea3f46_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrichmentgoldenfield',
            constraint=models.UniqueConstraint(fields=('record', 'field'), name='enrichment_golden_uniq'),
        ),
        migrations.AddIndex(
            model_name='enrichmentclaim',
            index=models.Index(fields=['record', 'field'], name='warehouse_e_record__99312f_idx'),
        ),
        migrations.AddIndex(
            model_name='enrichmentclaim',
            index=models.Index(fields=['field', 'verified'], name='warehouse_e_field_8babbf_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrichmentclaim',
            constraint=models.UniqueConstraint(fields=('record', 'field', 'value_hash', 'provider'), name='enrichment_claim_uniq'),
        ),
    ]
